### PR TITLE
Install the AWS CLI

### PR DESCRIPTION
**Pull request by talen-sa**
- Adds the AWS CLI

### CODE REVIEW

**Review by darin-sai — APPROVED** [review]
This looks good. I haven't tried to run it myself.

**Comment by darin-sai** [comment]
I'm taking a look at this now.

**Review by darin-sai — CHANGES_REQUESTED** [review]
won't work because phython isn't installed.

```
Step 16/27 : RUN ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
 ---> Running in 8e7117115d7f
/usr/bin/env: ‘python’: No such file or directory
The command '/bin/sh -c ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws' returned a non-zero code: 127
```

**Comment by talen-sa** [comment]
Sorry about that, I guess python was getting pulled in as a dependency later on in the Dockerfile - should work now!

**Review by darin-sai — APPROVED** [review]
Looks good! that's the change I made too. If you feel like it, you could fix the indenting in the Dockerfile to be a consistent 4 spaces 😛

**Comment by talen-sa** [comment]
Sure thing - I believe everything should be 4 spaces now, let me know if I missed anything

**Pull request merged**
